-- Setup script for loyalty and promo code system

-- Add loyalty columns to CLIENTS table if they don't exist
ALTER TABLE CLIENTS ADD (
    TOTAL_ACHATS NUMBER(10,2) DEFAULT 0,
    NIVEAU_FIDELITE VARCHAR2(20) DEFAULT 'BRONZE'
);

-- Create promo codes table
CREATE TABLE CODE_PROMO (
    CODE VARCHAR2(20) PRIMARY KEY,
    DESCRIPTION VARCHAR2(100),
    POURCENTAGE_REMISE NUMBER(5,2) NOT NULL,
    DATE_DEBUT DATE,
    DATE_FIN DATE,
    ACTIF NUMBER(1) DEFAULT 1,
    CONSTRAINT CHK_REMISE CHECK (POURCENTAGE_REMISE >= 0 AND POURCENTAGE_REMISE <= 100)
);

-- Create loyalty levels configuration table
CREATE TABLE NIVEAU_FIDELITE (
    NIVEAU VARCHAR2(20) PRIMARY KEY,
    SEUIL_MINIMUM NUMBER(10,2) NOT NULL,
    POURCENTAGE_REMISE NUMBER(5,2) NOT NULL
);

-- Insert default loyalty levels
INSERT INTO NIVEAU_FIDELITE VALUES ('BRONZE', 0, 0);
INSERT INTO NIVEAU_FIDELITE VALUES ('ARGENT', 1000, 5);
INSERT INTO NIVEAU_FIDELITE VALUES ('OR', 5000, 10);
INSERT INTO NIVEAU_FIDELITE VALUES ('PLATINE', 10000, 15);

COMMIT;

-- Verify the setup
SELECT 'CLIENTS table updated' AS STATUS FROM DUAL
UNION ALL
SELECT 'CODE_PROMO table created' AS STATUS FROM DUAL
UNION ALL
SELECT 'NIVEAU_FIDELITE table created' AS STATUS FROM DUAL
UNION ALL
SELECT 'Loyalty levels inserted: ' || COUNT(*) AS STATUS FROM NIVEAU_FIDELITE;